
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                - accepted_values:
                    values: [1, 2]
                    quote: false

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - relationships:
                    to: ref('my_first_dbt_model')
                    field: id

    - name: customer_total_spend
      description: "Total customer spending"
      columns:
          - name: c_custkey
            tests:
                - unique
                - not_null

    - name: cumulative_orders_by_date
      description: "total order revenue as at a particular date"
      columns:
          - name: o_orderdate
            tests:
                - unique
                - not_null

    - name: dates 
      columns:
          - name: d_date
            tests:
                - unique
                - not_null     
    
    - name: times 
      columns:
          - name: t_time
            tests:
                - unique
                - not_null   