
version: 2

models:
    - name: dates 
      description: 'table about dates running incrementally'
      columns:
          - name: d_date
            tests:
                - unique
                - not_null     
    